# coding: utf-8

"""
    Amalgam Index API

    Amalgam Index (Amgix). The Hybrid Semantic Search Platform, API

    The version of the OpenAPI document: 1.0.0-beta3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from amgix_client.models.metadata_index import MetadataIndex
from amgix_client.models.vector_config import VectorConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CollectionConfig(BaseModel):
    """
    API model for collection configuration - uses VectorConfig.
    """ # noqa: E501
    vectors: List[VectorConfig] = Field(description="List of vector configurations for this collection")
    store_content: Optional[StrictBool] = Field(default=True, description="Whether to store document content in the database.")
    metadata_indexes: Optional[List[MetadataIndex]] = Field(default=None, description="List of metadata fields to index for filtering and sorting")
    __properties: ClassVar[List[str]] = ["vectors", "store_content", "metadata_indexes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CollectionConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in vectors (list)
        _items = []
        if self.vectors:
            for _item_vectors in self.vectors:
                if _item_vectors:
                    _items.append(_item_vectors.to_dict())
            _dict['vectors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metadata_indexes (list)
        _items = []
        if self.metadata_indexes:
            for _item_metadata_indexes in self.metadata_indexes:
                if _item_metadata_indexes:
                    _items.append(_item_metadata_indexes.to_dict())
            _dict['metadata_indexes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CollectionConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "vectors": [VectorConfig.from_dict(_item) for _item in obj["vectors"]] if obj.get("vectors") is not None else None,
            "store_content": obj.get("store_content") if obj.get("store_content") is not None else True,
            "metadata_indexes": [MetadataIndex.from_dict(_item) for _item in obj["metadata_indexes"]] if obj.get("metadata_indexes") is not None else None
        })
        return _obj


