# coding: utf-8

"""
    Amgix API

    Amgix (Amalgam Index) - Open-Source Hybrid Search System

    The version of the OpenAPI document: 1.6.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from amgix_client.models.join import Join
from amgix_client.models.metadata_filter import MetadataFilter
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DocumentFetchRequest(BaseModel):
    """
    Request body for paginated document fetching.
    """ # noqa: E501
    page_size: Optional[Annotated[int, Field(le=1000, strict=True, ge=1)]] = Field(default=100, description="Number of documents per page (1 to 1000)")
    after: Optional[StrictStr] = Field(default=None, description="Pagination token returned by a previous fetch call. Omit or set to null to start from the beginning.")
    metadata_filter: Optional[MetadataFilter] = None
    document_tags: Optional[Annotated[List[StrictStr], Field(max_length=50)]] = Field(default=None, description="Optional filter to include only documents with specific tags (max 50 tags).")
    document_tags_match_all: Optional[StrictBool] = Field(default=False, description="If True, documents must have ALL specified tags (AND). If False, ANY (OR).")
    join: Optional[Join] = None
    with_vectors: Optional[StrictBool] = Field(default=False, description="When true, include stored vector values on each returned document.")
    __properties: ClassVar[List[str]] = ["page_size", "after", "metadata_filter", "document_tags", "document_tags_match_all", "join", "with_vectors"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentFetchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata_filter
        if self.metadata_filter:
            _dict['metadata_filter'] = self.metadata_filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of join
        if self.join:
            _dict['join'] = self.join.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentFetchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "page_size": obj.get("page_size") if obj.get("page_size") is not None else 100,
            "after": obj.get("after"),
            "metadata_filter": MetadataFilter.from_dict(obj["metadata_filter"]) if obj.get("metadata_filter") is not None else None,
            "document_tags": obj.get("document_tags"),
            "document_tags_match_all": obj.get("document_tags_match_all") if obj.get("document_tags_match_all") is not None else False,
            "join": Join.from_dict(obj["join"]) if obj.get("join") is not None else None,
            "with_vectors": obj.get("with_vectors") if obj.get("with_vectors") is not None else False
        })
        return _obj


