# coding: utf-8

"""
    Amgix API

    Amgix (Amalgam Index) - Open-Source Hybrid Search System

    The version of the OpenAPI document: 1.6.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FacetOptions(BaseModel):
    """
    Tuning for faceting; used only when SearchQuery.facets is True.
    """ # noqa: E501
    prefetch_multiplier: Optional[Annotated[int, Field(le=10, strict=True, ge=1)]] = Field(default=2, description="Multiplier on query.limit setting the per-arm candidate window for facet computation. The window is floored to at least 50 candidates. Larger multipliers yield more accurate distributions at higher cost (1 to 10).")
    max_values: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=10, description="Maximum distinct values returned per facet field, kept as the top-N by count (1 to 100).")
    __properties: ClassVar[List[str]] = ["prefetch_multiplier", "max_values"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FacetOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FacetOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prefetch_multiplier": obj.get("prefetch_multiplier") if obj.get("prefetch_multiplier") is not None else 2,
            "max_values": obj.get("max_values") if obj.get("max_values") is not None else 10
        })
        return _obj


