# coding: utf-8

"""
    Amalgam Index API

    Amalgam Index (Amgix). Open-Source Hybrid Search System

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from amgix_client.models.node_metric_series import NodeMetricSeries
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodeView(BaseModel):
    """
    Snapshot of a single cluster node as last reported to the leader.
    """ # noqa: E501
    role: StrictStr = Field(description="Node role: 'index', 'query', 'all' for encoder nodes; 'api' for API nodes")
    is_leader: Optional[StrictBool] = Field(default=False, description="Whether this node is the current encoder leader")
    last_seen: Union[StrictFloat, StrictInt] = Field(description="Unix timestamp of the last heartbeat received from this node")
    meta: Optional[Dict[str, Any]] = Field(default=None, description="Forward-compatible node metadata bag (for load/capacity/gpu/memory/model details and future node status values)")
    metrics: Optional[List[NodeMetricSeries]] = Field(default=None, description="Metric series for this node; empty for API nodes")
    __properties: ClassVar[List[str]] = ["role", "is_leader", "last_seen", "meta", "metrics"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in metrics (list)
        _items = []
        if self.metrics:
            for _item_metrics in self.metrics:
                if _item_metrics:
                    _items.append(_item_metrics.to_dict())
            _dict['metrics'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "role": obj.get("role"),
            "is_leader": obj.get("is_leader") if obj.get("is_leader") is not None else False,
            "last_seen": obj.get("last_seen"),
            "meta": obj.get("meta"),
            "metrics": [NodeMetricSeries.from_dict(_item) for _item in obj["metrics"]] if obj.get("metrics") is not None else None
        })
        return _obj


