# coding: utf-8

"""
    Amgix API

    Amgix (Amalgam Index) - Open-Source Hybrid Search System

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from amgix_client.models.custom_vector import CustomVector
from amgix_client.models.facet_options import FacetOptions
from amgix_client.models.join1 import Join1
from amgix_client.models.metadata_filter1 import MetadataFilter1
from amgix_client.models.vector_search_option import VectorSearchOption
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchQuery(BaseModel):
    """
    Configuration for a search query. Defines the query string and vector options. This is the model that will be sent by end users to the search API endpoint.
    """ # noqa: E501
    query: Annotated[str, Field(strict=True, max_length=10000)] = Field(description="The search query string (max 10000 characters)")
    vector_options: Optional[List[VectorSearchOption]] = Field(default=None, description="List of vectors, fields, and weights to use for searching. If empty, equal weights will be auto-generated for all available vectors.")
    custom_vectors: Optional[List[CustomVector]] = Field(default=None, description="Pre-generated custom vectors for this search query (optional)")
    limit: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=10, description="Maximum number of results to return (1 to 100)")
    score_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Optional minimum score threshold. Results below this score will be excluded")
    document_tags: Optional[Annotated[List[StrictStr], Field(max_length=50)]] = Field(default=None, description="Optional filter to include only documents with specific tags (max 50 tags, each max 100 characters; cannot contain pipe characters)")
    document_tags_match_all: Optional[StrictBool] = Field(default=False, description="If True, documents must have ALL specified tags (AND). If False, documents must have ANY of the specified tags (OR).")
    metadata_filter: Optional[MetadataFilter1] = None
    join: Optional[Join1] = None
    exclude: Optional[List[StrictStr]] = Field(default=None, description="Optional list of document fields to omit from search results (and from documents attached via 'joined'). Allowed values: name, description, content, tags, metadata.")
    group_field: Optional[StrictStr] = Field(default=None, description="Optional indexed metadata field to group results by. When set, results are capped at group_max per distinct value of this field, refetching up to group_max_fetches times if needed to fill the requested limit.")
    group_max: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=3, description="Maximum number of results allowed per group_field value")
    group_max_fetches: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=2, description="Total number of fetches (including the first) allowed while grouping")
    facets: Optional[StrictBool] = Field(default=False, description="If True, compute facet counts over the candidate pool for every field declared in the collection's metadata_indexes. Counts are returned in SearchResponse.facet_counts.")
    facet_options: Optional[FacetOptions] = Field(default=None, description="Tuning for faceting (prefetch window and max values per field). Used only when facets is True.")
    raw_scores: Optional[StrictBool] = Field(default=False, description="Whether to include individual vector scores in results")
    fusion_mode: Optional[StrictStr] = Field(default='rrf', description="How to combine multi-vector search results. 'rrf' = reciprocal rank fusion (rank-based). 'linear' = min-max normalize each retriever's scores on its prefetch list, then sum weight * normalized score.")
    __properties: ClassVar[List[str]] = ["query", "vector_options", "custom_vectors", "limit", "score_threshold", "document_tags", "document_tags_match_all", "metadata_filter", "join", "exclude", "group_field", "group_max", "group_max_fetches", "facets", "facet_options", "raw_scores", "fusion_mode"]

    @field_validator('exclude')
    def exclude_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['name', 'description', 'content', 'tags', 'metadata']):
                raise ValueError("each list item must be one of ('name', 'description', 'content', 'tags', 'metadata')")
        return value

    @field_validator('fusion_mode')
    def fusion_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['rrf', 'linear']):
            raise ValueError("must be one of enum values ('rrf', 'linear')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in vector_options (list)
        _items = []
        if self.vector_options:
            for _item_vector_options in self.vector_options:
                if _item_vector_options:
                    _items.append(_item_vector_options.to_dict())
            _dict['vector_options'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_vectors (list)
        _items = []
        if self.custom_vectors:
            for _item_custom_vectors in self.custom_vectors:
                if _item_custom_vectors:
                    _items.append(_item_custom_vectors.to_dict())
            _dict['custom_vectors'] = _items
        # override the default output from pydantic by calling `to_dict()` of metadata_filter
        if self.metadata_filter:
            _dict['metadata_filter'] = self.metadata_filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of join
        if self.join:
            _dict['join'] = self.join.to_dict()
        # override the default output from pydantic by calling `to_dict()` of facet_options
        if self.facet_options:
            _dict['facet_options'] = self.facet_options.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "vector_options": [VectorSearchOption.from_dict(_item) for _item in obj["vector_options"]] if obj.get("vector_options") is not None else None,
            "custom_vectors": [CustomVector.from_dict(_item) for _item in obj["custom_vectors"]] if obj.get("custom_vectors") is not None else None,
            "limit": obj.get("limit") if obj.get("limit") is not None else 10,
            "score_threshold": obj.get("score_threshold"),
            "document_tags": obj.get("document_tags"),
            "document_tags_match_all": obj.get("document_tags_match_all") if obj.get("document_tags_match_all") is not None else False,
            "metadata_filter": MetadataFilter1.from_dict(obj["metadata_filter"]) if obj.get("metadata_filter") is not None else None,
            "join": Join1.from_dict(obj["join"]) if obj.get("join") is not None else None,
            "exclude": obj.get("exclude"),
            "group_field": obj.get("group_field"),
            "group_max": obj.get("group_max") if obj.get("group_max") is not None else 3,
            "group_max_fetches": obj.get("group_max_fetches") if obj.get("group_max_fetches") is not None else 2,
            "facets": obj.get("facets") if obj.get("facets") is not None else False,
            "facet_options": FacetOptions.from_dict(obj["facet_options"]) if obj.get("facet_options") is not None else None,
            "raw_scores": obj.get("raw_scores") if obj.get("raw_scores") is not None else False,
            "fusion_mode": obj.get("fusion_mode") if obj.get("fusion_mode") is not None else 'rrf'
        })
        return _obj


