# coding: utf-8

"""
    Amalgam Index API

    Amalgam Index (Amgix). Open-Source Hybrid Search System

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SystemInfoResponse(BaseModel):
    """
    SystemInfoResponse
    """ # noqa: E501
    amgix_version: StrictStr = Field(description="API / deployment version string")
    database_kind: StrictStr = Field(description="Database product derived from configured URL scheme (no connection string)")
    database_version: StrictStr = Field(description="Version reported by the database backend after probe")
    database_features: Dict[str, StrictBool] = Field(description="Feature flags detected at probe time (e.g. dense vector support)")
    rabbitmq_version: StrictStr = Field(description="AMQP broker version from Connection.Start server_properties (e.g. RabbitMQ)")
    collection_count: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of user collections")
    __properties: ClassVar[List[str]] = ["amgix_version", "database_kind", "database_version", "database_features", "rabbitmq_version", "collection_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemInfoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amgix_version": obj.get("amgix_version"),
            "database_kind": obj.get("database_kind"),
            "database_version": obj.get("database_version"),
            "database_features": obj.get("database_features"),
            "rabbitmq_version": obj.get("rabbitmq_version"),
            "collection_count": obj.get("collection_count")
        })
        return _obj


