# coding: utf-8

"""
    Amgix API

    Amgix (Amalgam Index) - Open-Source Hybrid Search System

    The version of the OpenAPI document: 1.6.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VectorData(BaseModel):
    """
    Vector data for a specific vector. Contains the precalculated vector values, which can be either dense or sparse.
    """ # noqa: E501
    vector_name: StrictStr = Field(description="Name of the vector")
    var_field: StrictStr = Field(description="Field this vector is for (name, description, content)", alias="field")
    vector_type: StrictStr = Field(description="Type of vector (dense_model, sparse_model, full_text, trigrams, whitespace, wmtr, dense_custom, sparse_custom)")
    dense_vector: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="Dense vector values as a list of floats")
    sparse_indices: Optional[List[StrictInt]] = Field(default=None, description="Sparse vector indices (token positions)")
    sparse_values: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="Sparse vector values (token weights)")
    __properties: ClassVar[List[str]] = ["vector_name", "field", "vector_type", "dense_vector", "sparse_indices", "sparse_values"]

    @field_validator('var_field')
    def var_field_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['name', 'description', 'content']):
            raise ValueError("must be one of enum values ('name', 'description', 'content')")
        return value

    @field_validator('vector_type')
    def vector_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['dense_model', 'sparse_model', 'full_text', 'trigrams', 'whitespace', 'wmtr', 'keyword', 'dense_custom', 'sparse_custom', 'noop']):
            raise ValueError("must be one of enum values ('dense_model', 'sparse_model', 'full_text', 'trigrams', 'whitespace', 'wmtr', 'keyword', 'dense_custom', 'sparse_custom', 'noop')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VectorData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VectorData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "vector_name": obj.get("vector_name"),
            "field": obj.get("field"),
            "vector_type": obj.get("vector_type"),
            "dense_vector": obj.get("dense_vector"),
            "sparse_indices": obj.get("sparse_indices"),
            "sparse_values": obj.get("sparse_values")
        })
        return _obj


